name: GRL_2023
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0=py310hecd8cb5_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.2=py310hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310hca72f7f_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py310hecd8cb5_0
  - babel=2.11.0=py310hecd8cb5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310hecd8cb5_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py310h4e76f89_0
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py310h90acd4f_1005
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.12.7=h033912b_0
  - cartopy=0.21.1=py310h578c2b2_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310ha78151a_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - comm=0.1.2=py310hecd8cb5_0
  - cryptography=39.0.0=py310h23bb4e6_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py310he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310hecd8cb5_0
  - et_xmlfile=1.1.0=py310hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fftw=3.3.10=nompi_h4fa670e_106
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.38.0=py310h90acd4f_1
  - freetype=2.10.4=h4cff582_1
  - geos=3.11.1=hf0c8a7f_0
  - giflib=5.2.1=hbcb3906_2
  - icu=58.2=h0a44026_3
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - ipykernel=6.19.2=py310h20db666_0
  - ipython=8.8.0=py310hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py310hecd8cb5_1
  - jinja2=3.1.2=py310hecd8cb5_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=hac89ed1_2
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.16.0=py310hecd8cb5_0
  - jupyter_client=7.4.8=py310hecd8cb5_0
  - jupyter_core=5.1.1=py310hecd8cb5_0
  - jupyter_server=1.23.4=py310hecd8cb5_0
  - jupyterlab=3.5.3=py310hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.16.5=py310hecd8cb5_0
  - kiwisolver=1.4.4=py310ha23aa8a_1
  - kneed=0.7.0=pyh9f0ad1d_0
  - krb5=1.19.3=hb49756b_0
  - lcms2=2.14=h90f4b2a_0
  - lerc=3.0=he9d5cce_0
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcurl=7.87.0=ha585b31_0
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.8=h9ed2024_5
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=hecd8cb5_6
  - libgfortran=5.0.0=11_3_0_h97931a8_27
  - libgfortran5=11.3.0=h082f757_27
  - libiconv=1.16=hca72f7f_2
  - libnghttp2=1.46.0=ha29bfda_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.10.0=h52ee1ee_2
  - libtiff=4.4.0=h2cd0358_2
  - libwebp=1.2.4=hfa4350a_0
  - libwebp-base=1.2.4=h775f41a_0
  - libxml2=2.9.14=hbf8cd5e_0
  - libxslt=1.1.35=h5b33f42_0
  - llvm-openmp=15.0.7=h61d9ccf_0
  - lxml=4.9.1=py310h65b224f_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - markupsafe=2.1.1=py310hca72f7f_0
  - matplotlib-base=3.5.3=py310h6438751_0
  - matplotlib-inline=0.1.6=py310hecd8cb5_0
  - mistune=0.8.4=py310hca72f7f_1000
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py310hca72f7f_0
  - mkl_fft=1.3.1=py310hf879493_0
  - mkl_random=1.2.2=py310hc081a56_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.8=py310hecd8cb5_0
  - nbclient=0.5.13=py310hecd8cb5_0
  - nbconvert=6.5.4=py310hecd8cb5_0
  - nbformat=5.7.0=py310hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=py310hecd8cb5_0
  - notebook=6.5.2=py310hecd8cb5_0
  - notebook-shim=0.2.2=py310hecd8cb5_0
  - numexpr=2.8.4=py310h9638375_0
  - numpy=1.23.5=py310h9638375_0
  - numpy-base=1.23.5=py310ha98c3c9_0
  - openpyxl=3.0.10=py310hca72f7f_0
  - openssl=1.1.1t=hfd90126_0
  - packaging=22.0=py310hecd8cb5_0
  - pandas=1.5.2=py310h3ea8b11_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py310hcec6c5f_2
  - pip=22.3.1=py310hecd8cb5_0
  - platformdirs=2.5.2=py310hecd8cb5_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - proj=9.0.1=h05f0992_1
  - prometheus_client=0.14.1=py310hecd8cb5_0
  - prompt-toolkit=3.0.36=py310hecd8cb5_0
  - psutil=5.9.0=py310hca72f7f_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.3.1=py310hac86e01_1
  - pyrsistent=0.18.0=py310hca72f7f_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.9=h218abb5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310hecd8cb5_0
  - python_abi=3.10=2_cp310
  - pytz=2022.7=py310hecd8cb5_0
  - pyzmq=23.2.0=py310he9d5cce_0
  - readline=8.2=hca72f7f_0
  - requests=2.28.2=pyhd8ed1ab_0
  - scikit-learn=1.2.0=py310hcec6c5f_0
  - scipy=1.10.0=py310h64422d5_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py310hecd8cb5_0
  - shapely=2.0.1=py310h4e43f2a_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py310hecd8cb5_1
  - soupsieve=2.3.2.post1=py310hecd8cb5_0
  - sqlite=3.40.1=h880c91c_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py310h936d966_2
  - terminado=0.17.1=py310hecd8cb5_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tinycss2=1.2.1=py310hecd8cb5_0
  - tk=8.6.12=h5d9f67b_0
  - tomli=2.0.1=py310hecd8cb5_0
  - tornado=6.2=py310hca72f7f_0
  - tqdm=4.64.1=py310hecd8cb5_0
  - traitlets=5.7.1=py310hecd8cb5_0
  - typing-extensions=4.4.0=py310hecd8cb5_0
  - typing_extensions=4.4.0=py310hecd8cb5_0
  - tzdata=2022g=h04d1e81_0
  - unicodedata2=15.0.0=py310h90acd4f_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310hecd8cb5_1
  - websocket-client=0.58.0=py310hecd8cb5_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h6c40b1e_1
  - zeromq=4.3.4=h23ab428_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.2=hcb37349_0
  - pip:
    - future==0.18.3
    - pmagpy==4.2.109
